Loaded module: cuda/11.8
python: can't open file '/zhome/af/3/214532/PyHPC/mini-project/visualize.py': [Errno 2] No such file or directory
Command exited with non-zero status 2
	Command being timed: "python visualize.py"
	User time (seconds): 0.00
	System time (seconds): 0.01
	Percent of CPU this job got: 46%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.04
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 7400
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 45
	Minor (reclaiming a frame) page faults: 780
	Voluntary context switches: 122
	Involuntary context switches: 48
	Swaps: 0
	File system inputs: 8408
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 2
